vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
    - ms-azuretools.vscode-docker

tasks:
  - env:
      dir: /workspace
    init: |
      mkdir -p $dir/aws-cli
      mkdir -p $dir/bin
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
      tempdir=$(mktemp -d)
      unzip /tmp/awscliv2.zip -d $tempdir/
      rm -f /tmp/awscliv2.zip
      $tempdir/aws/install -i /workspace/aws-cli -b /workspace/bin --update
    command: |
      complete -C '/workspace/bin/aws_completer' aws
      /workspace/aws-bootcamp-cruddur-2023/backend-flask/bin/update-sg-rule
      export PATH=/workspace/bin:$PATH
      clear
  - name: install-postgres-client
    command: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-15 libpq-dev
      exit
  - name: Setup db storage directories
    command: |
      mkdir -p /workspace/docker/dynamodb
      mkdir -p /workspace/docker/psqldb
      exit

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    onOpen: ignore
    visibility: public
  - name: pgsql
    port: 5432
    onOpen: ignore
    visibility: private
  - name: ddb
    port: 8000
    onOpen: ignore
    visibility: private
