
vscode:
  extensions:
    - 42Crunch.vscode-openapi

tasks:
  - name: install aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      dir=$(mktemp -d)
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip -d $dir
      sudo $dir/aws/install
      rm -rf $dir
      rm -f awscliv2.zip
      cd $GITPOD_REPO_ROOT