AWSTemplateFormatVersion: 2010-09-09
Description: |
  - CodeStar Connection V2 Github
  - CodePipeline
  - Codebuild
Parameters:
  GitHubBranch:
    Type: String
    Default: prod
  GithubRepo:
    Type: String
    Default: "lightweavr/aws-bootcamp-cruddur-2023"
  ServiceStack:
    Type: String
    Default: Cruddurservice
  FrontendStack:
    Type: String
    Default: Cruddurfrontend
Resources:
  CodeBuildBackendImageStack:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BuildName: backend-flask
        BuildSpec: backend-flask/buildspec.yml
        ArtifactBucketName: !Ref ArtifactBucket
      TemplateURL: codebuild.yml

  CodeBuildFrontendStack:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BuildName: frontend-react-js
        BuildSpec: frontend-react-js/buildspec.yml
        ArtifactBucketName: !Ref ArtifactBucket
        CodeBuildImage: aws/codebuild/amazonlinux2-x86_64-standard:5.0
      TemplateURL: codebuild.yml

  CodeStarConnection:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codestarconnections-connection.html
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: !Sub ${AWS::StackName}-connection
      ProviderType: GitHub

  ArtifactBucket:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: true
        BlockPublicAcls: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  Pipeline:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: ApplicationSource
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Provider: CodeStarSourceConnection
                Owner: AWS
                Version: "1"
              OutputArtifacts:
                - Name: Source
              Configuration:
                ConnectionArn: !Ref CodeStarConnection
                FullRepositoryId: !Ref GithubRepo
                BranchName: !Ref GitHubBranch
                OutputArtifactFormat: "CODE_ZIP"
        - Name: Build
          Actions:
            - Name: Build-Backend
              # https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CodeBuild.html
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: Source
              OutputArtifacts:
                - Name: BackendBuildArtifact
              Configuration:
                ProjectName: !GetAtt CodeBuildBackendImageStack.Outputs.CodeBuildProjectName
                BatchEnabled: false
            - Name: Build-Frontend
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: Source
              OutputArtifacts:
                - Name: FrontendBuildArtifact
              Configuration:
                ProjectName: !GetAtt CodeBuildFrontendStack.Outputs.CodeBuildProjectName
                BatchEnabled: false
        - Name: Deploy
          Actions:
            - Name: Deploy-Backend
              # https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-ECS.html
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Provider: ECS
                Owner: AWS
                Version: "1"
              InputArtifacts:
                - Name: BackendBuildArtifact
              Configuration:
                # In Minutes
                DeploymentTimeout: "10"
                ClusterName:
                  Fn::ImportValue: !Sub ${ServiceStack}ClusterName
                ServiceName:
                  Fn::ImportValue: !Sub ${ServiceStack}ServiceName
            - Name: Deploy-Frontend
              # https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-S3Deploy.html
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Provider: S3
                Owner: AWS
                Version: "1"
              InputArtifacts:
                - Name: FrontendBuildArtifact
              Configuration:
                BucketName:
                  Fn::ImportValue: !Sub ${FrontendStack}BucketName
                Extract: true

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ["sts:AssumeRole"]
            Effect: Allow
            Principal:
              Service: [codepipeline.amazonaws.com]
        Version: "2012-10-17"
      Path: /
      Policies:
        - PolicyName: !Sub ${AWS::StackName}EcsDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - ecs:DescribeServices
                  - ecs:DescribeTaskDefinition
                  - ecs:DescribeTasks
                  - ecs:ListTasks
                  - ecs:RegisterTaskDefinition
                  - ecs:UpdateService
                Effect: Allow
                Resource: "*"
        - PolicyName: !Sub ${AWS::StackName}CodeStarPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - codestar-connections:UseConnection
                Effect: Allow
                Resource: !Ref CodeStarConnection
        - PolicyName: !Sub ${AWS::StackName}CodePipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:*
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - cloudformation:*
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                Effect: Allow
                Resource: "*"
        - PolicyName: !Sub ${AWS::StackName}CodePipelineBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                  - codebuild:RetryBuild
                  - codebuild:BatchGetBuilds
                  - codebuild:BatchGetBuildBatches
                  - codebuild:StartBuildBatch
                Effect: Allow
                Resource: !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/*"

  EventbridgeTrigger:
    Type: AWS::Scheduler::Schedule
    Properties:
      Description: !Sub Trigger CodePipeline ${Pipeline} on a schedule
      FlexibleTimeWindow:
        MaximumWindowInMinutes: 240
        Mode: FLEXIBLE
      ScheduleExpression: "rate(1 day)"
      ScheduleExpressionTimezone: UTC
      Target:
        Arn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}
        RoleArn: !GetAtt EventbridgeIAMRole.Arn

  EventbridgeIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
      Path: /cruddur/eventbridge/
      Policies:
        - PolicyName: TriggerCodePipeline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - codepipeline:StartPipelineExecution
                Effect: Allow
                Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}
