AWSTemplateFormatVersion: 2010-09-09
Description: |
  - S3 Bucket & Bucket Policy
  - CloudFront Distribution
  - Route 53 Alias setup
Parameters:
  CertificateArn:
    Type: String
    # Ideally this could be managed, but the stack is in us-west-2, and cloudfront requires ACM certs be in us-east-1
    Default: arn:aws:acm:us-east-1:017145807427:certificate/5d7b917c-2a9e-49ee-ad40-74767877c64c
  DNSName:
    Type: String
    Default: cpbc.lightweaver.ca

Resources:
  StaticSiteBucketPolicy:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Sid: AllowCloudFrontServicePrincipalReadOnly
          Effect: Allow
          Principal:
            Service: "cloudfront.amazonaws.com"
          Action: "s3:GetObject"
          Resource: !Sub "${StaticSiteBucket.Arn}/*"
          Condition:
            StringEquals:
              "AWS:SourceArn": !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}
  StaticSiteBucket:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: true
        BlockPublicAcls: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Cloudfront
  CloudFrontOriginAccessControl:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-originaccesscontrol.html
    Type: AWS::CloudFront::OriginAccessControl
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-originaccesscontrol-originaccesscontrolconfig.html
      OriginAccessControlConfig:
        Description: String
        Name: Cloudfront S3 OriginAccessControl
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudfrontDomainIPv4Alias:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
    Type: AWS::Route53::RecordSet
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Delete
    Properties:
      HostedZoneName: !Sub ${DNSName}.
      Name: !Sub ${DNSName}.
      Type: A
      AliasTarget:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
        # Specify Z2FDTNDATAQYW2. This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution.
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  CloudfrontDomainIpv6Alias:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
    Type: AWS::Route53::RecordSet
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Delete
    Properties:
      HostedZoneName: !Sub ${DNSName}.
      Name: !Sub ${DNSName}.
      Type: AAAA
      AliasTarget:
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
        # Specify Z2FDTNDATAQYW2. This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution.
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  Distribution:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Retain
    UpdateReplacePolicy: Delete
    Properties:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html
      DistributionConfig:
        Aliases:
          - !Sub ${DNSName}
        Comment: Frontend React Js for Cruddur
        Enabled: true
        IPV6Enabled: true
        HttpVersion: http2and3
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-origin.html
        Origins:
          - DomainName: !GetAtt StaticSiteBucket.RegionalDomainName
            Id: StaticSiteBucketOrigin
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: StaticSiteBucketOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
Outputs:
  DNSName:
    Value: !Ref DNSName
    Export:
      Name: !Sub "${AWS::StackName}DNSName"
  BucketName:
    Value: !Ref StaticSiteBucket
    Export:
      Name: !Sub "${AWS::StackName}BucketName"
